/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
/**
 * Feedback object.
 *
 * @minProperties 1
 */
export type FeedbackData = {
  /**
   * Rating of the feedback.
   *
   * @minimum 0
   * @example 3
   */
  rating?: number;
  /**
   * Sentiment of the feedback.
   */
  sentiment?: boolean;
  /**
   * Reasons of the feedback.
   *
   * @minItems 1
   */
  reasons?: string[];
  /**
   * Suggestion of the feedback.
   *
   * @example Add more details
   */
  suggestion?: string;
};

/**
 * Feedback object.
 */
export type FeedbackMetaData = {
  /**
   * Unique identifier of the feedback.
   *
   * @example c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd
   */
  id: string;
  /**
   * Date of the feedback creation.
   *
   * @format date-time
   * @example 2020-01-01T00:00:00.000Z
   */
  createdAt: string;
  /**
   * Date of the feedback update.
   *
   * @format date-time
   * @example 2020-01-01T00:00:00.000Z
   */
  updatedAt?: string;
  /**
   * Unique identifier of the user.
   *
   * @example abc
   */
  userId?: string;
  /**
   * IP address of the user.
   *
   * @example 91.201.190.10
   */
  userIP: string;
  /**
   * Unique identifier of the tenant.
   *
   * @example a0b73bce-3217-4c3b-801b-3c202881b240
   */
  tenantId: string;
  /**
   * User agent of the device.
   *
   * @example Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
   */
  userAgent: string;
  /**
   * Page of the feedback.
   *
   * @example /docs/page-name
   */
  page?: string;
  /**
   * Category of the feedback.
   *
   * @example Support
   */
  category?: string;
  /**
   * operationId of the API.
   *
   * @example getUser
   */
  apiOperationId?: string;
};

/**
 * Feedback object.
 *
 * @minProperties 1
 */
export type Feedback = FeedbackData & FeedbackMetaData;

/**
 * Pagination object.
 */
export type Pagination = {
  /**
   * Current page.
   *
   * @example 1
   */
  page?: number;
  /**
   * Number of items per page.
   *
   * @example 50
   */
  perPage?: number;
  /**
   * Total number of items.
   *
   * @example 50
   */
  total?: number;
};
