/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
/**
 * @pattern ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
 * @example c73bcdcc-2669-4bf6-81d3-e4ae73fb11fd
 */
export type ResourceId = string;

export type Rating = number[];

export type Sentiment = (true | false)[];

export type Reason = string[];

export type UserId = string[];

export type UserIP = string[];

export type Page = string[];

export type Category = string[];

export type ApiOperationId = string[];

/**
 * @default 1
 * @example 1
 */
export type Page2 = number;

/**
 * @default 50
 * @example 10
 */
export type PerPage = number;

/**
 * @default desc
 */
export type Order = 'asc' | 'desc';

/**
 * @default createdAt
 */
export type OrderBy = 'rating' | 'createdAt';
