/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type BadRequest = {
  message: 'Bad Request';
  data?: {
    /**
     * @example invalid_type
     */
    code?: string;
    /**
     * @example number
     */
    expected?: string;
    /**
     * @example string
     */
    received?: string;
    path?: string[];
    /**
     * @example Expected number, received string
     */
    message?: string;
  };
};

export type Unauthorized = {
  message: 'Unauthorized';
};

export type NotFound = {
  message: 'Not found';
};

export type TooManyRequests = {
  message: 'Too Many Requests';
};

export type InternalServerError = {
  message: 'Internal Server Error';
};

export type NoContent = void;
