/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Data } from '../models/data';

/**
 * Creates an instance of BadRequest
 */
interface BadRequest {
  message: string;
  data?: Data;
}

export class BadRequestError extends ApiError<BadRequest> {}
