/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of InternalServer
 */
interface InternalServer {
  message: string;
}

export class InternalServerError extends ApiError<InternalServer> {}
