/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of TooManyRequests
 */
interface TooManyRequests {
  message: string;
}

export class TooManyRequestsError extends ApiError<TooManyRequests> {}
