/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Credentials. */
export interface Credentials {
  /** Private API Key. */
  privateKey: string;
}

export const credentialsSchema: Schema<Credentials> = object({
  privateKey: ['privateKey', string()],
});
