/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** Feedback object. */
export interface FeedbackContext {
  /** Page of the feedback. */
  page?: string;
  /** Category of the feedback. */
  category?: string;
  /** operationId of the API. */
  apiOperationId?: string;
  /** Any list of tags to group feedbacks by. */
  tags?: string[];
  /** Unique identifier of the user. */
  userId?: string;
}

export const feedbackContextSchema: Schema<FeedbackContext> = object({
  page: ['page', optional(string())],
  category: ['category', optional(string())],
  apiOperationId: ['apiOperationId', optional(string())],
  tags: ['tags', optional(array(string()))],
  userId: ['userId', optional(string())],
});
