/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

/** Feedback object. */
export interface FeedbackData {
  /** Rating of the feedback. */
  rating?: number;
  /** Sentiment of the feedback. */
  sentiment?: boolean;
  /** Reasons of the feedback. */
  reasons?: string[];
  /** Suggestion of the feedback. */
  suggestion?: string;
}

export const feedbackDataSchema: Schema<FeedbackData> = object({
  rating: ['rating', optional(number())],
  sentiment: ['sentiment', optional(boolean())],
  reasons: ['reasons', optional(array(string()))],
  suggestion: ['suggestion', optional(string())],
});
