/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Feedback, feedbackSchema } from './feedback';
import { Pagination, paginationSchema } from './pagination';

export interface FeedbackResponse {
  data?: Feedback[];
  /** Pagination object. */
  pagination?: Pagination;
}

export const feedbackResponseSchema: Schema<FeedbackResponse> = object({
  data: ['data', optional(array(lazy(() => feedbackSchema)))],
  pagination: ['pagination', optional(lazy(() => paginationSchema))],
});
