/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Pagination object. */
export interface Pagination {
  /** Current page. */
  page?: number;
  /** Number of items per page. */
  perPage?: number;
  /** Total number of items. */
  total?: number;
}

export const paginationSchema: Schema<Pagination> = object({
  page: ['page', optional(number())],
  perPage: ['perPage', optional(number())],
  total: ['total', optional(number())],
});
