/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

/** Tenant object. */
export interface Tenant {
  /** Unique identifier of the tenant. */
  id: string;
  /** Private API Key. */
  privateApiKey: string;
  /** Email of the user. */
  email: string;
  /** Allowed domains. */
  domains?: string[];
  /** Name of the user. */
  rapidUser: string;
  /** Status of the tenant. */
  active: boolean;
  /** Date of the tenant creation. */
  createdAt: string;
  /** Date of the feedback update. */
  updatedAt: string;
}

export const tenantSchema: Schema<Tenant> = object({
  id: ['id', string()],
  privateApiKey: ['privateApiKey', string()],
  email: ['email', string()],
  domains: ['domains', optional(array(string()))],
  rapidUser: ['rapidUser', string()],
  active: ['active', boolean()],
  createdAt: ['createdAt', string()],
  updatedAt: ['updatedAt', string()],
});
