/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for XORDEREnum
 */
export enum XORDEREnum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for XORDEREnum
 */
export const xORDEREnumSchema: Schema<XORDEREnum> = stringEnum(XORDEREnum);
