/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for XORDERBYEnum
 */
export enum XORDERBYEnum {
  Rating = 'rating',
  CreatedAt = 'createdAt',
}

/**
 * Schema for XORDERBYEnum
 */
export const xORDERBYEnumSchema: Schema<XORDERBYEnum> = stringEnum(XORDERBYEnum);
