/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { passThroughInterceptor } from './core';
import { AuthenticatorInterface } from './core';

/** None authentication provider */
export const noneAuthenticationProvider = () => passThroughInterceptor;
//@ts-ignore
export const customAuthenticationProvider = ({
  xApiKey,
  xRapidAPIKey,
}: {
  xApiKey: string;
  xRapidAPIKey: string;
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }

    return (request, options, next) => {

      return next(request, options);
    };
  };
};
