/**
 * Feedback APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { mergeHeaders } from './core';
import { passThroughInterceptor } from './core';
import { AuthenticatorInterface } from './core';

/** None authentication provider */
export const noneAuthenticationProvider = () => passThroughInterceptor;

export const customHeaderAuthenticationProvider = ({
  xRapidAPIKey,
  xAPIKEY,
  xRapidAPIHost,
}: {
  xRapidAPIKey: string;
  xAPIKEY: string;
  xRapidAPIHost: string;
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }

    return (request, options, next) => {
      const customHeaderParams = {
        'X-RapidAPI-Key': xRapidAPIKey,
        'X-API-KEY': xAPIKEY,
        'X-RapidAPI-Host': xRapidAPIHost,
      };
      mergeHeaders(request.headers ?? {}, customHeaderParams);

      return next(request, options);
    };
  };
};
